version: 2
jobs:
  test_ci:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/GSA/grace-citest
    steps:
      - checkout
      - run:
          name: Export Environment Variables
          command: |
            echo "exporting CI_USER=${CIRCLE_USER}"
            echo 'export CI_USER="$CIRCLE_USER"' >> $BASH_ENV
      - run:
          name: Run Tests
          command: |
            pwd && make test
workflows:
  version: 2
  test_and_apply:
    jobs:
      - test_ci