version: 2
jobs:
  test_ci:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/GSA/grace-citest
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
            pwd && make test
workflows:
  version: 2
  test_and_apply:
    jobs:
      - test_ci